#!/bin/bash

# Mock Interview AI Setup Script
# This script helps you set up the project quickly

echo "🚀 Setting up Mock Interview AI Application..."

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js 18+ first."
    exit 1
fi

# Check Node.js version
NODE_VERSION=$(node --version | cut -d'.' -f1 | cut -d'v' -f2)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo "❌ Node.js version 18+ is required. Current version: $(node --version)"
    exit 1
fi

echo "✅ Node.js $(node --version) detected"

# Install dependencies
echo "📦 Installing dependencies..."
npm install

if [ $? -eq 0 ]; then
    echo "✅ Dependencies installed successfully"
else
    echo "❌ Failed to install dependencies"
    exit 1
fi

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file..."
    cat > .env << EOF
# Database Configuration
DATABASE_URL=postgresql://username:password@localhost:5432/mock_interview_ai

# AI Service Configuration
GEMINI_API_KEY=your_gemini_api_key_here

# Application Configuration
NODE_ENV=development
PORT=5000

# PostgreSQL Configuration (auto-generated by Neon)
PGHOST=localhost
PGPORT=5432
PGDATABASE=mock_interview_ai
PGUSER=username
PGPASSWORD=password
EOF
    echo "✅ .env file created! Please edit it with your actual values."
else
    echo "⚠️  .env file already exists. Please verify your configuration."
fi

# Check if database URL is configured
if grep -q "your_gemini_api_key_here" .env; then
    echo ""
    echo "⚠️  IMPORTANT: You need to configure your environment variables!"
    echo "   1. Get a Gemini API key from: https://makersuite.google.com/app/apikey"
    echo "   2. Set up a PostgreSQL database (recommended: https://neon.tech)"
    echo "   3. Update the .env file with your actual values"
    echo ""
fi

# Display next steps
echo ""
echo "🎉 Setup complete! Next steps:"
echo ""
echo "1. Configure your environment variables in .env"
echo "2. Push database schema: npm run db:push"
echo "3. Start development server: npm run dev"
echo ""
echo "📚 For detailed setup instructions, see README.md"
echo "🚀 For deployment options, see DEPLOYMENT.md"
echo ""
echo "Need help? Check the issues page: https://github.com/yourusername/mock-interview-ai/issues"